"""Add expires_at to banned_ips

Revision ID: 273bba5a4815
Revises: 51edd1deecd3
Create Date: 2026-03-29 17:23:06.976861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273bba5a4815'
down_revision = '51edd1deecd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banned_ips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banned_ips', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
